import { Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer, Tooltip } from 'recharts';
import { FiDownload, FiRotateCcw } from 'react-icons/fi';

const pdfSafe = (text) => String(text || '').replace(/[\\()]/g, '\\$&').replace(/[^\x20-\x7E]/g, ' ');
const downloadReport = (interview) => {
  const lines = [`Dream & Infinity - Interview Report`, `${interview.targetRole} | ${interview.targetCompany}`, `Interview type: ${interview.interviewType}`, `Overall score: ${interview.scores?.overall || 0}%`, '', 'Score breakdown:', ...Object.entries(interview.scores || {}).map(([key, value]) => `${key}: ${value}%`), '', 'Strengths:', ...(interview.feedback?.strengths || []), '', 'Focus areas:', ...(interview.feedback?.weaknesses || [])];
  const content = lines.slice(0, 42).map((line, index) => `BT /F1 11 Tf 50 ${760 - index * 17} Td (${pdfSafe(line)}) Tj ET`).join('\n');
  const objects = [`<< /Type /Catalog /Pages 2 0 R >>`, `<< /Type /Pages /Kids [3 0 R] /Count 1 >>`, `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>`, `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`, `<< /Length ${content.length} >>\nstream\n${content}\nendstream`];
  let pdf = '%PDF-1.4\n'; const offsets = [0]; objects.forEach((object, index) => { offsets.push(pdf.length); pdf += `${index + 1} 0 obj\n${object}\nendobj\n`; }); const xref = pdf.length; pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.slice(1).map((offset) => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;
  const url = URL.createObjectURL(new Blob([pdf], { type: 'application/pdf' })); const link = document.createElement('a'); link.href = url; link.download = 'dream-infinity-interview-report.pdf'; link.click(); URL.revokeObjectURL(url);
};

export const InterviewResult = ({ interview, onRestart }) => {
  const scores = interview.scores || {}; const radar = Object.entries(scores).filter(([key]) => key !== 'overall').map(([key, value]) => ({ name: key, value })); const turns = interview.turns || interview.transcript || [];
  return <div className="result-page"><section className="result-hero"><div className="result-ring" style={{ '--score': `${(scores.overall || 0) * 3.6}deg` }}><div><strong>{scores.overall || 0}</strong><span>Overall</span></div></div><div><p className="dash-kicker">INTERVIEW COMPLETE</p><h1>Here is how you performed.</h1><p>{interview.targetRole} · {interview.targetCompany} · {interview.interviewType}</p><button onClick={() => downloadReport(interview)}><FiDownload/> Download PDF report</button><button className="result-restart" onClick={onRestart}><FiRotateCcw/> New interview</button></div></section><div className="result-grid"><section className="interview-panel"><h3>Performance radar</h3><ResponsiveContainer width="100%" height={300}><RadarChart data={radar}><PolarGrid stroke="#ffffff1f"/><PolarAngleAxis dataKey="name" tick={{ fill: '#d8b4fe', fontSize: 10 }}/><Tooltip contentStyle={{ background: '#181421', border: '1px solid #ffffff1f', borderRadius: 10 }}/><Radar dataKey="value" stroke="#a78bfa" fill="#8b5cf6" fillOpacity={.35}/></RadarChart></ResponsiveContainer></section><section className="interview-panel score-list"><h3>Score breakdown</h3>{Object.entries(scores).map(([name, value]) => <div key={name}><span>{name}</span><b>{value}%</b><i><em style={{ width: `${value}%` }}/></i></div>)}</section></div><div className="result-grid"><Feedback title="Your strengths" items={interview.feedback?.strengths} color="positive"/><Feedback title="Focus areas" items={interview.feedback?.weaknesses} color="warning"/></div><div className="result-grid"><Feedback title="Suggested improvements" items={interview.feedback?.suggestedImprovements} color="info"/><Feedback title="Practice next" items={interview.feedback?.practiceQuestions} color="info"/></div><section className="interview-panel"><p className="dash-kicker">INTERVIEW TIMELINE</p><h3>Questions and answers</h3>{turns.length ? turns.map((turn, index) => <article className="timeline-item" key={`${turn.question}-${index}`}><b>Question {index + 1}</b><p>{turn.question}</p><small>{turn.answeredAt ? new Date(turn.answeredAt).toLocaleTimeString() : 'Answered during interview'}</small></article>) : <p className="empty-copy">No turn history was recorded.</p>}</section><section className="interview-panel roadmap-result"><p className="dash-kicker">NEXT STEPS</p><h3>Learning roadmap</h3>{interview.feedback?.learningRoadmap?.map((item, index) => <article key={item}><span>{index + 1}</span><p>{item}</p></article>)}</section></div>;
};
const Feedback = ({ title, items = [], color }) => <section className={`interview-panel feedback-card ${color}`}><h3>{title}</h3>{items?.length ? items.map((item, index) => <div key={item}><span>{index + 1}</span><p>{item}</p></div>) : <p className="empty-copy">No feedback was generated.</p>}</section>;
