import mongoose from 'mongoose';

const companySchema = new mongoose.Schema({ name: { type: String, required: true, unique: true, trim: true }, slug: { type: String, required: true, unique: true, index: true }, overview: String, topics: [{ type: String, trim: true }], followers: { type: Number, default: 0 } }, { timestamps: true, versionKey: false });
const postSchema = new mongoose.Schema({
  author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true, index: true },
  type: { type: String, enum: ['experience', 'question', 'discussion', 'poll', 'article', 'news', 'guide', 'tip', 'notes', 'resource'], default: 'discussion', index: true },
  title: { type: String, required: true, trim: true, maxlength: 180 }, content: { type: String, required: true, maxlength: 20000 },
  company: { type: String, trim: true, index: true }, role: String, experienceLevel: String, interviewDate: Date, interviewMode: String, rounds: Number, result: { type: String, enum: ['selected', 'rejected', 'pending', 'not_applicable'], default: 'not_applicable' }, location: String, salary: String,
  tags: [{ type: String, trim: true, lowercase: true }], difficulty: { type: String, enum: ['easy', 'medium', 'hard', ''], default: '' }, votes: { type: Number, default: 0 }, helpfulCount: { type: Number, default: 0 }, commentCount: { type: Number, default: 0 }, bookmarkCount: { type: Number, default: 0 }, status: { type: String, enum: ['approved', 'pending', 'removed'], default: 'approved' },
}, { timestamps: true, versionKey: false });
postSchema.index({ title: 'text', content: 'text', tags: 'text', company: 'text' });
const commentSchema = new mongoose.Schema({ post: { type: mongoose.Schema.Types.ObjectId, ref: 'CommunityPost', required: true, index: true }, author: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, parent: { type: mongoose.Schema.Types.ObjectId, ref: 'CommunityComment', default: null }, body: { type: String, required: true, maxlength: 5000 }, mentions: [String], votes: { type: Number, default: 0 }, isDeleted: { type: Boolean, default: false } }, { timestamps: true, versionKey: false });
const voteSchema = new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, targetType: { type: String, enum: ['post', 'comment'], required: true }, target: { type: mongoose.Schema.Types.ObjectId, required: true }, value: { type: Number, enum: [-1, 1], required: true } }, { timestamps: true, versionKey: false }); voteSchema.index({ user: 1, targetType: 1, target: 1 }, { unique: true });
const bookmarkSchema = new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, targetType: { type: String, enum: ['post', 'company'], default: 'post' }, target: { type: String, required: true } }, { timestamps: true, versionKey: false }); bookmarkSchema.index({ user: 1, targetType: 1, target: 1 }, { unique: true });
const followSchema = new mongoose.Schema({ user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, targetType: { type: String, enum: ['company', 'topic', 'user', 'tag'], required: true }, target: { type: String, required: true } }, { timestamps: true, versionKey: false }); followSchema.index({ user: 1, targetType: 1, target: 1 }, { unique: true });
const reportSchema = new mongoose.Schema({ reporter: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true }, post: { type: mongoose.Schema.Types.ObjectId, ref: 'CommunityPost', required: true }, reason: { type: String, enum: ['spam', 'fake_experience', 'abuse', 'duplicate', 'other'], required: true }, details: String, status: { type: String, enum: ['open', 'reviewed', 'resolved'], default: 'open' } }, { timestamps: true, versionKey: false });
export const Community = mongoose.model('Community', companySchema); export const CommunityPost = mongoose.model('CommunityPost', postSchema); export const CommunityComment = mongoose.model('CommunityComment', commentSchema); export const CommunityVote = mongoose.model('CommunityVote', voteSchema); export const CommunityBookmark = mongoose.model('CommunityBookmark', bookmarkSchema); export const CommunityFollow = mongoose.model('CommunityFollow', followSchema); export const CommunityReport = mongoose.model('CommunityReport', reportSchema);
