import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import toast from 'react-hot-toast';
import { FiClock, FiTrendingUp } from 'react-icons/fi';
import { analyzeResume, clearResumeError, deleteResume, loadResumes, selectResume, uploadResume } from '../../redux/slices/resumeSlice.js';
import { ResumeUploadCard } from '../../components/resume/ResumeUploadCard.jsx';
import { ATSScoreCard } from '../../components/resume/ATSScoreCard.jsx';
import { SkillsSection } from '../../components/resume/SkillsSection.jsx';
import { SuggestionsSection } from '../../components/resume/SuggestionsSection.jsx';
import { ResumeHistory } from '../../components/resume/ResumeHistory.jsx';
import { ResumePreview } from '../../components/resume/ResumePreview.jsx';

export const ResumeAnalyzerPage = () => { const dispatch = useDispatch(); const { resumes, currentResume, loading, uploading, uploadProgress, error } = useSelector((state) => state.resume); useEffect(() => { dispatch(loadResumes()); }, [dispatch]); useEffect(() => { if (error) { toast.error(error); dispatch(clearResumeError()); } }, [error, dispatch]); const upload = async (file, targetRole) => { const action = await dispatch(uploadResume({ file, targetRole })); if (uploadResume.fulfilled.match(action)) toast.success('Resume analyzed successfully.'); }; const remove = async (id) => { if (!window.confirm('Delete this resume and its analysis?')) return; const action = await dispatch(deleteResume(id)); if (deleteResume.fulfilled.match(action)) toast.success('Resume deleted.'); }; const reanalyze = async (resumeId) => { const action = await dispatch(analyzeResume({ resumeId })); if (analyzeResume.fulfilled.match(action)) toast.success('Analysis refreshed.'); }; const extracted = currentResume?.extracted || {}; return <div className="resume-page space-y-7"><section className="resume-hero"><div><p className="dash-kicker">GEMINI-POWERED RESUME REVIEW</p><h1>Turn your resume into an <span>interview magnet.</span></h1><p>Upload a resume to receive ATS insights, role-specific skill feedback, and a practical improvement plan.</p></div><div className="resume-hero-stats"><span><FiTrendingUp/> ATS scoring</span><span><FiClock/> Fast analysis</span></div></section><ResumeUploadCard onUpload={upload} uploading={uploading} progress={uploadProgress}/>{loading && !resumes.length ? <p className="empty-copy">Loading your resume history…</p> : <><div className="resume-grid"><ATSScoreCard score={currentResume?.atsScore} breakdown={currentResume?.scoreBreakdown}/><ResumePreview resume={currentResume}/></div><div className="resume-grid lower"><SkillsSection skills={currentResume?.skills} missingSkills={currentResume?.missingSkills}/><SuggestionsSection suggestions={currentResume?.suggestions}/></div><section className="resume-panel extracted-panel"><h3>Resume insights</h3><div>{[['Education', extracted.education], ['Experience', extracted.experience], ['Projects', extracted.projects], ['Certifications', extracted.certifications], ['Achievements', extracted.achievements]].map(([label, values]) => <article key={label}><b>{label}</b><p>{values?.length ? values.join(' · ') : 'No specific information identified yet.'}</p></article>)}</div></section><ResumeHistory resumes={resumes} currentId={currentResume?._id} onSelect={(id) => dispatch(selectResume(id))} onDelete={remove} onAnalyze={reanalyze}/></>}</div>; };
