import compression from 'compression';
import cors from 'cors';
import express from 'express';
import rateLimit from 'express-rate-limit';
import helmet from 'helmet';
import { errorHandler, notFoundHandler } from './middleware/errorHandler.js';
import { authRouter } from './routes/authRoutes.js';
import { aiRouter } from './routes/aiRoutes.js';
import { resumeRouter } from './routes/resumeRoutes.js';
import { skillGapRouter } from './routes/skillGapRoutes.js';
import { interviewRouter } from './routes/interviewRoutes.js';
import { codingRouter } from './routes/codingRoutes.js';
import { interviewRoomRouter } from './routes/interviewRoomRoutes.js';
import { communityRouter } from './routes/communityRoutes.js';
import { companyRouter } from './routes/companyRoutes.js';
import { gamificationRouter } from './routes/gamificationRoutes.js';
import { analyticsRouter } from './routes/analyticsRoutes.js';
import { profileRouter } from './routes/profileRoutes.js';
import { notificationRouter } from './routes/notificationRoutes.js';
import { uploadRouter } from './routes/uploadRoutes.js';

export const app = express();

app.set('trust proxy', 1);
app.use(helmet({
  crossOriginResourcePolicy: { policy: "cross-origin" }
}));
app.use(cors({ origin: process.env.CLIENT_URL?.split(',') || 'http://localhost:5173' }));
app.use(compression());
app.use(express.json({ limit: '1mb' }));
app.use('/uploads', express.static('uploads'));
app.use(rateLimit({ windowMs: 15 * 60 * 1000, limit: process.env.NODE_ENV === 'production' ? 100 : 10000, standardHeaders: 'draft-8', legacyHeaders: false }));

app.get('/health', (_req, res) => res.status(200).json({ success: true, status: 'ok' }));
app.use('/api/v1/auth', authRouter);
app.use('/api/v1/ai', aiRouter);
app.use('/api/ai', aiRouter);
app.use('/api/v1/resume', resumeRouter);
app.use('/api/resume', resumeRouter);
app.use('/api/v1/skill-gap', skillGapRouter);
app.use('/api/skill-gap', skillGapRouter);
app.use('/api/v1/interview', interviewRouter);
app.use('/api/interview', interviewRouter);
app.use('/api/v1/coding', codingRouter);
app.use('/api/coding', codingRouter);
app.use('/api/v1/interview-room', interviewRoomRouter);
app.use('/api/interview-room', interviewRoomRouter);
app.use('/api/v1/community', communityRouter);
app.use('/api/community', communityRouter);
app.use('/api/v1/company', companyRouter);
app.use('/api/company', companyRouter);
app.use('/api/v1/gamification', gamificationRouter);
app.use('/api/gamification', gamificationRouter);
app.use('/api/v1/analytics', analyticsRouter);
app.use('/api/analytics', analyticsRouter);
app.use('/api/v1/profile', profileRouter);
app.use('/api/profile', profileRouter);
app.use('/api/v1/notifications', notificationRouter);
app.use('/api/notifications', notificationRouter);
app.use('/api/v1/upload', uploadRouter);
app.use('/api/upload', uploadRouter);
app.use(notFoundHandler);
app.use(errorHandler);
