import { Company, CompanyPreparation } from '../models/Company.js'; import { CommunityPost } from '../models/Community.js'; import { AppError } from '../utils/AppError.js'; import { createAnalysis, roadmapFor } from '../services/companyService.js'; import { grantXp, rewards } from '../services/gamificationService.js';
const list = ['Google','Microsoft','Amazon','Meta','Netflix','Adobe','Oracle','Apple','Salesforce','Atlassian','Uber','LinkedIn','TCS','Infosys','Capgemini','Accenture','Wipro','Cognizant','Deloitte','JP Morgan','Goldman Sachs']; const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const defaults = (name) => ({ name, slug: slug(name), logo: name.slice(0, 1), overview: `${name} preparation center with current interview intelligence and a personalized plan.`, hiringProcess: ['Profile screening', 'Technical evaluation', 'Team interviews', 'Hiring decision'], rounds: ['Recruiter conversation', 'Technical round', 'Problem solving', 'Behavioral / hiring manager'], eligibility: 'Role-specific skills, a relevant resume, and interview readiness.', averagePackage: 'Varies by role and location', hiringTrends: 'Hiring signals are updated from community activity.', topics: ['DSA', 'System Design', 'React', 'Communication'], interviewStyle: 'Structured, skills-focused', codingFocus: 'Data structures and problem solving', behavioralFocus: 'Leadership and impact stories', preparationWeeks: 5, questions: [] });
export const companies = async (_req, res, next) => { try { const rows = await Company.find().select('name slug logo overview topics interviewStyle preparationWeeks').sort({ name: 1 }); const known = new Map(rows.map((row) => [row.name, row])); res.json({ success: true, companies: list.map((name) => known.get(name) || defaults(name)) }); } catch (error) { next(error); } };
export const company = async (req, res, next) => { try { const profile = await Company.findOne({ slug: req.params.id.toLowerCase() }) || defaults(req.params.id.replace(/-/g, ' ')); const experiences = await CommunityPost.find({ company: new RegExp(`^${profile.name}$`, 'i'), status: 'approved' }).populate('author', 'name level').sort({ createdAt: -1 }).limit(8); res.json({ success: true, company: profile, experiences }); } catch (error) { next(error); } };
export const readiness = async (req, res, next) => { try { const profile = await Company.findOne({ slug: req.body.companyId }); if (!profile) throw new AppError('Choose a supported company.', 404); const analysis = await createAnalysis({ user: req.user, company: profile, role: req.body.role || 'Software Engineer' }); const roadmap = roadmapFor(profile, analysis); const preparation = await CompanyPreparation.create({ user: req.user.id, company: profile.id, role: req.body.role || 'Software Engineer', readiness: analysis, roadmap, predictedQuestions: profile.questions.slice(0, 5).map((question) => question.text).concat(profile.topics.slice(0, 3).map((topic) => `Explain a recent ${topic} decision in one of your projects.`)) }); await grantXp(req.user, rewards.companyReadiness); res.status(201).json({ success: true, preparation, company: profile }); } catch (error) { next(error); } };
export const roadmap = async (req, res, next) => { try { const preparation = await CompanyPreparation.findOne({ user: req.user.id, company: req.body.companyId }).sort({ createdAt: -1 }); if (!preparation) throw new AppError('Generate readiness before creating a roadmap.', 404); res.json({ success: true, roadmap: preparation.roadmap, preparation }); } catch (error) { next(error); } };
export const questions = async (req, res, next) => { try { const profile = await Company.findOne({ slug: req.query.company }); if (!profile) throw new AppError('Company not found.', 404); let questions = profile.questions || []; if (req.query.difficulty) questions = questions.filter((item) => item.difficulty === req.query.difficulty); questions = questions.sort((a, b) => req.query.sort === 'recent' ? b._id.getTimestamp() - a._id.getTimestamp() : b.popularity - a.popularity); res.json({ success: true, questions, topics: profile.topics }); } catch (error) { next(error); } };
export const compare = async (req, res, next) => { try { const names = String(req.query.companies || '').split(',').filter(Boolean); const rows = await Promise.all(names.map(async (id) => await Company.findOne({ slug: id }) || defaults(id.replace(/-/g, ' ')))); res.json({ success: true, companies: rows }); } catch (error) { next(error); } };
