import { Interview } from '../models/Interview.js';
import { AppError } from '../utils/AppError.js';
import { difficulties, evaluateAnswer, generateFinalFeedback, generateQuestion, interviewTypes } from '../services/interviewService.js';
import { grantXp, rewards } from '../services/gamificationService.js';

const valid = (body) => { if (!interviewTypes.includes(body.interviewType) || !difficulties.includes(body.difficulty)) throw new AppError('Choose a supported interview type and difficulty.', 422); };
export const startInterview = async (req, res, next) => { try { valid(req.body); const interview = await Interview.create({ user: req.user.id, ...req.body }); const generated = await generateQuestion({ interview, user: req.user }); interview.currentQuestion = generated.question; await interview.save(); return res.status(201).json({ success: true, interview, question: generated.question }); } catch (error) { return next(error); } };
export const nextQuestion = async (req, res, next) => { try { const interview = await Interview.findOne({ _id: req.body.interviewId, user: req.user.id, status: 'in_progress' }); if (!interview) throw new AppError('Active interview not found.', 404); const generated = await generateQuestion({ interview, user: req.user }); interview.currentQuestion = generated.question; await interview.save(); return res.status(200).json({ success: true, question: generated.question, focus: generated.focus }); } catch (error) { return next(error); } };
export const answerQuestion = async (req, res, next) => { try { const interview = await Interview.findOne({ _id: req.body.interviewId, user: req.user.id, status: 'in_progress' }); if (!interview || !interview.currentQuestion) throw new AppError('Active interview question not found.', 404); const evaluation = await evaluateAnswer({ interview, question: interview.currentQuestion, answer: req.body.answer, user: req.user }); const turn = { question: interview.currentQuestion, answer: req.body.answer, askedAt: new Date(), answeredAt: new Date(), evaluation }; interview.turns.push(turn); interview.transcript.push(turn); interview.currentQuestion = null; await interview.save(); return res.status(200).json({ success: true, evaluation, turn }); } catch (error) { return next(error); } };
 export const finishInterview = async (req, res, next) => { try { const interview = await Interview.findOne({ _id: req.body.interviewId, user: req.user.id, status: 'in_progress' }); if (!interview) throw new AppError('Active interview not found.', 404); const result = await generateFinalFeedback({ interview }); interview.scores = result.scores; interview.feedback = result.feedback; interview.status = 'completed'; interview.completedAt = new Date(); interview.actualDurationSeconds = Math.max(0, Number(req.body.actualDurationSeconds) || 0); await interview.save(); const completed = (req.user.interviewStats?.completed || 0) + 1; const oldAverage = req.user.interviewStats?.averageScore || 0; req.user.interviewStats.completed = completed; req.user.interviewStats.averageScore = Math.round(((oldAverage * (completed - 1)) + interview.scores.overall) / completed); await grantXp(req.user, rewards.aiInterview); return res.status(200).json({ success: true, interview }); } catch (error) { return next(error); } };
export const interviewHistory = async (req, res, next) => { try { const interviews = await Interview.find({ user: req.user.id }).sort({ createdAt: -1 }).select('-turns -transcript'); return res.status(200).json({ success: true, interviews }); } catch (error) { return next(error); } };
export const getInterview = async (req, res, next) => { try { const interview = await Interview.findOne({ _id: req.params.id, user: req.user.id }); if (!interview) throw new AppError('Interview not found.', 404); return res.status(200).json({ success: true, interview }); } catch (error) { return next(error); } };
export const interviewDashboard = async (req, res, next) => { try {
  const interviews = await Interview.find({ user: req.user.id, status: 'completed' }).sort({ completedAt: -1 }).select('targetCompany targetRole interviewType scores feedback completedAt');
  const total = interviews.length;
  const averageScore = total ? Math.round(interviews.reduce((sum, item) => sum + (item.scores?.overall || 0), 0) / total) : 0;
  const weakAreas = [...new Set(interviews.flatMap((item) => [...(item.feedback?.weaknesses || []), ...(item.feedback?.missedConcepts || [])]))].slice(0, 5);
  const daily = new Map();
  interviews.filter((item) => item.completedAt).forEach((item) => { const day = item.completedAt.toISOString().slice(0, 10); daily.set(day, (daily.get(day) || 0) + 1); });
  return res.status(200).json({ success: true, metrics: { total, averageScore, weakAreas, recent: interviews.slice(0, 5), progress: [...daily].slice(0, 7).reverse().map(([day, value]) => ({ day, value })) } });
} catch (error) { return next(error); } };
