import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { Radar, RadarChart, PolarGrid, PolarAngleAxis, ResponsiveContainer, Tooltip } from 'recharts';
import toast from 'react-hot-toast';
import { analyzeSkillGap, clearSkillGapError, loadSkillGapHistory, refreshRoadmap, selectAssessment } from '../../redux/slices/skillGapSlice.js';
import { AssessmentForm } from '../../components/skillgap/AssessmentForm.jsx';
import { ReadinessGauge } from '../../components/skillgap/ReadinessGauge.jsx';
import { CompanyReadiness } from '../../components/skillgap/CompanyReadiness.jsx';
import { SkillMap } from '../../components/skillgap/SkillMap.jsx';
import { RoadmapTimeline } from '../../components/skillgap/RoadmapTimeline.jsx';

export const SkillGapPage = () => { const dispatch = useDispatch(); const { assessments, currentAssessment, loading, error } = useSelector((state) => state.skillGap); useEffect(() => { dispatch(loadSkillGapHistory()); }, [dispatch]); useEffect(() => { if (error) { toast.error(error); dispatch(clearSkillGapError()); } }, [error, dispatch]); const run = async (data) => { const action = await dispatch(analyzeSkillGap(data)); if (analyzeSkillGap.fulfilled.match(action)) toast.success('Your readiness assessment is ready.'); }; const breakdown = currentAssessment?.readinessBreakdown || {}; const radar = Object.entries(breakdown).map(([name, value]) => ({ skill: name.replace(/([A-Z])/g, ' $1'), score: value })); return <div className="skillgap-page space-y-7"><section className="skillgap-hero"><div><p className="dash-kicker">AI INTERVIEW READINESS ENGINE</p><h1>Know what to learn <span>before your next interview.</span></h1><p>Dream Infinity combines your profile, latest resume, practice signals, target role, and company expectations into a focused plan.</p></div><div className="assessment-history">{assessments.slice(0, 3).map((item) => <button onClick={() => dispatch(selectAssessment(item._id))} className={currentAssessment?._id === item._id ? 'active' : ''} key={item._id}><b>{item.overallReadiness}%</b><span>{item.targetCompany}</span></button>)}</div></section><AssessmentForm onSubmit={run} loading={loading}/>{currentAssessment ? <><div className="skillgap-grid"><ReadinessGauge score={currentAssessment.overallReadiness} breakdown={breakdown}/><section className="skill-panel radar-panel"><header><div><p className="dash-kicker">CAPABILITY MAP</p><h3>Interview skill radar</h3></div></header><ResponsiveContainer width="100%" height={290}><RadarChart data={radar}><PolarGrid stroke="#ffffff1f"/><PolarAngleAxis dataKey="skill" tick={{ fill: '#d8b4fe', fontSize: 10 }}/><Tooltip contentStyle={{ background: '#181421', border: '1px solid #ffffff1f', borderRadius: 10 }}/><Radar dataKey="score" stroke="#a78bfa" fill="#8b5cf6" fillOpacity={.35}/></RadarChart></ResponsiveContainer></section></div><div className="skillgap-grid lower"><SkillMap assessment={currentAssessment}/><RoadmapTimeline roadmap={currentAssessment.roadmap} onRefresh={() => dispatch(refreshRoadmap(currentAssessment._id))} loading={loading}/></div><CompanyReadiness scores={currentAssessment.companyScores}/><section className="skill-panel recommendations-panel"><p className="dash-kicker">AI COACHING NOTES</p><h3>Top recommendations</h3><div>{currentAssessment.recommendations?.map((item, index) => <article key={item}><span>{index + 1}</span><p>{item}</p></article>)}</div></section></> : <section className="skill-panel skill-empty"><h2>Your readiness engine is waiting.</h2><p>Choose a target role and company above to create your first assessment. Uploading a resume first produces the most useful results.</p></section>}</div>; };
